<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetOfficeVersion>15.0</TargetOfficeVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.7.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Content\Button.css" />
    <None Include="wwwroot\Content\MessageBanner.css" />
    <None Include="wwwroot\Home.css" />
    <None Include="wwwroot\Home.html" />
    <None Include="wwwroot\Home.js" />
    <None Include="wwwroot\Images\AddinIcon.png" />
    <None Include="wwwroot\Images\Button16x16.png" />
    <None Include="wwwroot\Images\Button32x32.png" />
    <None Include="wwwroot\Images\Button80x80.png" />
    <None Include="wwwroot\Images\Close.png" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.intellisense.js" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.js" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.min.js" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.min.map" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.slim.js" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.slim.min.js" />
    <None Include="wwwroot\Scripts\jquery-3.6.0.slim.min.map" />
    <None Include="wwwroot\Scripts\MessageBanner.js" />
  </ItemGroup>

</Project>
